project:
  type: website
  output-dir: docs
  
site-url: https://kayleightompkins.github.io/personal_website/

website:
  title: "Kayleigh Tompkins"
  navbar:
    right:
     - text: "CV"
       href: CV.pdf
       target: _blank
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: Assignments.qmd
        text: Knowledge Mining Assignments

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true

editor: visual

